language: ruby
sudo: required
dist: trusty
cache:
- bundler
install:
- bundle install
rvm:
- 2.1
- 2.2
- 2.3
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
  - rvm use --default $TRAVIS_RUB_VERSION
  - echo 'export PATH="$PATH:/home/travis/.rvm/bin"' | sudo tee -a /etc/profile
  - echo 'source /home/travis/.rvm/scripts/rvm' | sudo tee -a /etc/profile
  - bundle exec rake default
  - bundle exec kitchen test
  - sudo chown -R travis:travis /home/travis/.rvm
  - gem build sensu-plugins-dcos.gemspec
  - gem install sensu-plugins-dcos-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: gEAG8w7v8luKjpTp1NvNQ3qMUoGpfsNWmBByhwXq+A/B2KeaLd5UnUSEFJIK2JkxLkTr1rIpiWxBQmuHKN+RReJm8nij0Awt+oHLKruWw3rOht+fnlXHlI67njbXwnmQPuG44SOX5tqesWzwMBd35dIrYNJyygvwSlDXIOQtHUA=
  gem: sensu-plugins-dcos
  on:
    tags: true
    all_branches: true
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3
    repo: sensu-plugins/sensu-plugins-dcos

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
