# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.3.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - gem install aws-sdk
          - bundler --version
          - bundle install
          - bundle exec rake
          - bundle exec rake build
          # Usage: sensu_upload.rb bucket artefact bucket_key
          - ruby s3_upload.rb dublin-devops-artifacts pkg/sensu-plugins-dcos-0.0.1.gem gems/sensu-plugins-dcos-0.0.1.gem